global:
  name: consul
  datacenter: dc1
  image: hashicorp/consul:1.10.3
  metrics:
    enabled: true
    enableAgentMetrics: true
server:
  replicas: 1
ui:
  enabled: true
  service:
    enabled: true
    type: NodePort 
connectInject:
  enabled: true
controller:
  enabled: true
prometheus:
  enabled: true
